Repository PnEcrins/RGAlt, pull requests merged in 2024-07, with the labels that each got.

#44 Feat/UI
  changelog.md
  front-end/angular.json
  front-end/m3-theme.scss
  front-end/public/banner.JPG
  front-end/public/financement.png
  front-end/public/labo.png
  front-end/public/parn.png
  front-end/public/pne.jpg
  front-end/public/sngm.png
  front-end/public/tutelle.png
  front-end/src/app/app.component.html
  front-end/src/app/app.component.ts
  front-end/src/app/pages/home/home.component.html
  front-end/src/app/pages/home/home.component.scss
  front-end/src/app/pages/home/home.component.ts
  front-end/src/app/pages/learn-more/learn-more.component.html
  front-end/src/app/pages/learn-more/learn-more.component.scss
  front-end/src/app/pages/legal-notice/legal-notice.component.html
  front-end/src/index.html
  front-end/src/styles.scss
Labels: enhancement

#47 fix: offline tiles
  front-end/src/app/pages/my-offline-data/my-offline-data.component.ts
  front-end/src/app/services/offline.service.ts
Labels: bug

#49 Feat/UI improv
  front-end/src/app/pages/home/home.component.scss
  front-end/src/app/pages/new-observation/new-observation.component.html
Labels: enhancement

#50 edit front end readme
  front-end/README.md
Labels: documentation

#59 handle sub category on primary category filter
  front-end/src/app/pages/my-observations/my-observations.component.ts
  front-end/src/app/pages/my-offline-data/my-offline-data.component.html
  front-end/src/app/pages/my-offline-data/my-offline-data.component.ts
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.html
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.ts
  front-end/src/app/services/observations.service.ts
Labels: bug

#60 Feat/ui2
  front-end/m3-theme.scss
  front-end/public/favicon.ico
  front-end/public/icons/icon-128x128.png
  front-end/public/icons/icon-144x144.png
  front-end/public/icons/icon-152x152.png
  front-end/public/icons/icon-192x192.png
  front-end/public/icons/icon-36x36.png
  front-end/public/icons/icon-384x384.png
  front-end/public/icons/icon-48x48.png
  front-end/public/icons/icon-512x512.png
  front-end/public/icons/icon-72x72.png
  front-end/public/icons/icon-96x96.png
  front-end/public/logo.png
  front-end/src/app/app.component.html
  front-end/src/app/pages/home/home.component.html
  front-end/src/app/pages/home/home.component.scss
  front-end/src/app/pages/new-observation/new-observation.component.html
  front-end/src/app/pages/new-observation/new-observation.component.ts
Labels: enhancement

#62 sort observations by alphabetical order on synthesis interface
  front-end/src/app/pages/login/login.component.html
  front-end/src/app/pages/synthesis-interface/dialogs/filter-dialog.html
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.scss
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.ts
Labels: bug

#63 rename obs -> evenements + make offline page accessible when not connected
  front-end/src/app/app.component.ts
  front-end/src/app/app.routes.ts
  front-end/src/app/pages/home/home.component.html
  front-end/src/app/pages/my-observations/my-observations.component.html
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.html
  front-end/src/app/pages/synthesis-interface/synthesis-interface.component.ts
Labels: enhancement
